### ISSUE TITLE
The `docker service create` reporting no-such Docker Image

### ISSUE THREAD

**Issue by collabnix** [crazy-max/swarm-cronjob#1]
### Behaviour

The `docker service create` CLI failed to find crazy-max/swarm-cronjob Docker Image from DockerHub.

#### Steps to reproduce this issue

1. Clone the Repository

2. Run the below command:

```
$ docker service create --name swarm_cronjob \
  --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
  --env "LOG_LEVEL=debug" \
  --env "LOG_NOCOLOR=false" \
  --constraint "node.role == manager" \
  crazy-max/swarm-cronjob
```

```
$ docker service create --name swarm_cronjob \
>   --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
>   --env "LOG_LEVEL=debug" \
>   --env "LOG_NOCOLOR=false" \
>   --constraint "node.role == manager" \
>   crazy-max/swarm-cronjob
image crazy-max/swarm-cronjob:latest could not be accessed on a registry to record
its digest. Each node will access crazy-max/swarm-cronjob:latest independently,
possibly leading to different nodes running different
versions of the image.

9kajseol4htx23ee8rmb6mwmy
overall progress: 0 out of 1 tasks
overall progress: 0 out of 1 tasks
overall progress: 0 out of 1 tasks
overall progress: 0 out of 1 tasks
1/1: No such image: crazy-max/swarm-cron
```

#### Expected behaviour

The `docker service create` command should bring up service successfully.

> Tell me what should happen

#### Actual behaviour

```
>   crazy-max/swarm-cronjob
image crazy-max/swarm-cronjob:latest could not be accessed on a registry to reco[manager1] (local) root@192.168.0.29 ~
$ docker service ls
ID                  NAME                MODE                REPLICAS            IMAGE
   PORTS
9kajseol4htx        swarm_cronjob       replicated          0/1                 crazy-max/swarm-cronjob:latest
```

> Tell me what happens instead

### Configuration

* Target Docker version (the host/cluster you manage) :  18.06
* Platform (windows/linux) :  Alpine Linux - Play with Docker Platform

### Docker Info
``
$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:20:43 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:28:38 2018
  OS/Arch:          linux/amd64
  Experimental:     true
[manager2] (local) root@192.168.0.33 ~
$
```

> Output of command docker info
```
manager2] (local) root@192.168.0.33 ~
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 01fys52vbw5lk7v6d9vf6egc1
 Is Manager: true
 ClusterID: 92tcpvpq257c9va1m3v2mntm1
 Managers: 3
 Nodes: 5
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.0.33
 Manager Addresses:
  192.168.0.29:2377
  192.168.0.32:2377
  192.168.0.33:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-139-generic
Operating System: Alpine Linux v3.8 (containerized)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.4GiB
Name: manager2
ID: CVAV:2WX7:43M5:G6JM:PS5M:3TL5:EGCG:FU7V:AC7P:QTLL:P7WU:QKM7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 43
 Goroutines: 152
 System Time: 2018-12-20T03:25:49.703326389Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.1
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
```

> Output of command docker info

### Logs

> Service logs (set LOG_LEVEL to debug)

**Comment by crazy-max** [comment]
@collabnix Yes small typo sorry ^^
`crazy-max/swarm-cronjob` > `crazymax/swarm-cronjob`

**Comment by collabnix** [comment]
http://collabnix.com/running-cron-jobs-container-on-5-node-docker-swarm-mode-cluster/
