### ISSUE TITLE
Replicas > 1

### ISSUE THREAD

**Issue by cjsfj** [crazy-max/swarm-cronjob#10]
Is it possible to run this on multiple replicas? 

My deployment has three manager nodes and three worker nodes. I'm curious if it's possible to run this with three replicas in order to accommodate scale. 

Alternatively, maybe a single replica can handle as much as one can throw at it?

Thanks for making this!

CJ

**Comment by crazy-max** [comment]
I'm not sure I've identified your need, but if it's about scalability, swarm itself will take care of it. Can you give me your use case?

**Comment by cjsfj** [comment]
Thanks so much for the reply!

Mostly I was curious if there is some sort of recommended cap as to the number of scheduled tasks this would operate without issues.. If I say, had 200 "cronjobs" would there be any issue?

If I were to hit that cap, I would think about running two replicas of this service. But then I'd be worried that jobs would be duplicated.

Let me know if this makes sense.

Thanks!

CJ

**Comment by crazy-max** [comment]
swarm-cronjob only calls Docker API to bring up your service so everything is handle by Docker engine. If your concern is about queue jobs size managed by swarm-cronjob, I have never encountered this kind of problem. In fact, I use the wonderful [robfig/cron](https://github.com/robfig/cron) lib to handle scheduled jobs and it works pretty well.

So in your case, the load distribution will be managed by swarm between your different nodes.

Thanks for your support!

**Comment by cjsfj** [comment]
thank you!
