### ISSUE TITLE
Scheduling in timezone

### ISSUE THREAD

**Issue by cjsfj** [crazy-max/swarm-cronjob#11]
Have their been any requests/thoughts around the ability to schedule tasks in a timezone? 

For example, if I have a swarm-cronjob instance that runs in UTC, I would like to schedule a service to run every week on Monday at Midnight California time, without doing the math myself to adjust the scheduling. 

I have users scheduling tasks in multiple time zones and this would be a great nice-to-have.

Thanks,

CJ

**Comment by crazy-max** [comment]
Hi @cjsfj, ok so you want to set a timezone for each service through a label like `swarm.cronjob.timezone=Europe/Paris`?

**Comment by cjsfj** [comment]
@crazy-max That's exactly it.

**Comment by crazy-max** [comment]
@cjsfj I think you can already do it using `CRON_TZ` to specify the timezone of a single schedule, which is sanctioned by the specification.

Example: `swarm.cronjob.schedule=CRON_TZ=Asia/Tokyo 0 0 * * * *`

See also robfig/cron#148

**Comment by cjsfj** [comment]
That's great. Thank you. I totally missed that.

**Comment by crazy-max** [comment]
@cjsfj Let me know if it works. I will add a note about this in the README.
