### ISSUE TITLE
log update of cronjob as Info instead of Debug

### ISSUE THREAD

**Issue by maiermic** [crazy-max/swarm-cronjob#113]
Is it intentionally that

```
Add cronjob with schedule ...
```

is [logged as Info](https://github.com/crazy-max/swarm-cronjob/blob/a62b403f08868250502cbfc90579993c815f5075/internal/app/app.go#L178), but

```
Update cronjob with schedule ...
```

is [logged as Debug](https://github.com/crazy-max/swarm-cronjob/blob/a62b403f08868250502cbfc90579993c815f5075/internal/app/app.go#L176) message?

Since no log appeared (in log level `info`), I first thought that the updated labels (`swarm.cronjob.schedule`) have not been recognized by swarm-cronjob.

**Comment by crazy-max** [comment]
@maiermic https://github.com/crazy-max/swarm-cronjob/issues/29#issuecomment-595607903
