### ISSUE TITLE
Multiple Schedules?

### ISSUE THREAD

**Issue by cjsfj** [crazy-max/swarm-cronjob#12]
Really enjoying this capability.

I do have one service that I want to have multiple schedules. Example:

0 * 17-20 5 9 * 
0 * 10-20 8 9 * 
0 * 16-22 9 9 * 
0 * 17-20 12 9 * 
0 * 10-20 15 9 * 
0 * 17-20 16 9 * 
0 * 17-20 19 9 * 
0 * 10-20 22 9 * 
0 * 17-20 23 9 * 
0 * 17-20 26 9 * 
0 * 10-20 29 9 * 

Would I need to specify multiple services with the same command but different schedules? Or is there a way to give a single service multiple schedules?

CJ

**Comment by crazy-max** [comment]
Hi @cjsfj,

> Would I need to specify multiple services with the same command but different schedules? Or is there a way to give a single service multiple schedules?

Yes, you need to specify multiple services but can you tell me more about your use case?

> Really enjoying this capability.

Thanks, glad you like it.

Also, is `CRON_TZ` working ? (see #11)

**Comment by cjsfj** [comment]
Thanks @crazy-max 

> tell me more about your use case

Our use case is that we have a job that need to run to coincide with business activities that are arbitrarily scheduled for different times on different dates. It's the same image and same command (same service) with the only exception being the schedule is not repeatable in enough of a way that could be consistent.

One option might be to create a parent script that runs on a repeatable schedule, and has its own mechanism to check to see if the actual command needs to be executed (in one of the weird windows).

> Also, is CRON_TZ working ?

We will find out at the turn of our fiscal quarter, which is the end of September ;) I will be sure to report back!

**Comment by crazy-max** [comment]
> Our use case is that we have a job that need to run to coincide with business activities that are arbitrarily scheduled for different times on different dates. It's the same image and same command (same service) with the only exception being the schedule is not repeatable in enough of a way that could be consistent.

Ok, Since your schedule is not constant / linear, you have to specify multiple services.

> One option might be to create a parent script that runs on a repeatable schedule, and has its own mechanism to check to see if the actual command needs to be executed (in one of the weird windows).

What you can use to manage multiple schedules is to use [Docker Application](https://github.com/docker/app) to generate these services for example.

> We will find out at the turn of our fiscal quarter, which is the end of September ;) I will be sure to report back!

Ok thanks!
