### ISSUE TITLE
Feature: log removed services

### ISSUE THREAD

**Issue by leshik** [crazy-max/swarm-cronjob#13]
Would be nice if `swarm-cronjob` could log removed services as well. Now when a service is added, the following line is printed:

```
INF Add cronjob with schedule 0 0,30 * * * * service=some_task
```

But when you deploy the same stack with the `--prune` option, and service gets deleted, nothing is printed, which is a bit confusing.

**Comment by leshik** [comment]
I also think another message should be printed to log in case the schedule for the existing service is modified.

**Comment by crazy-max** [comment]
@leshik Log for removed/disables services has been added in latest release.
