### ISSUE TITLE
documentation mistake in mariadb exemple

### ISSUE THREAD

**Issue by mathroc** [crazy-max/swarm-cronjob#132]
I think there’s a mistake in the mariadb example, the label `swarm.cronjob.schedule=* * * * *` seems wrong

according to https://pkg.go.dev/github.com/robfig/cron#hdr-CRON_Expression_Format, 6 fields are required but there’s only 5 here.

and it looks like it would run every minutes (or seconds?), maybe it should be something like that: `swarm.cronjob.schedule=0 0 3* * * *` to run it at 4 in the morning everyday

**Comment by crazy-max** [comment]
@mathroc Not a mistake, can be [5 or 6 fields (`cron.SecondOptional`)](https://github.com/crazy-max/swarm-cronjob/blob/969ddd239461238b7ae4f7b7d4c4c6ce30104f23/internal/app/app.go#L32).
