### ISSUE TITLE
Email/slack notifications on warnings & errors

### ISSUE THREAD

**Issue by didacrarbones** [crazy-max/swarm-cronjob#170]
First of all, thanks for the awesome project!

I have been using the image for a while, and I always thought that it would be awesome to get configurable notifications via email/slack when there's an issue running any of the jobs. In my case, some of the jobs hang sometimes due to disk usage issues, and I have to always find out because the service is down. I would love to get the notification as soon as possible to be able to restart the service.

Thanks!

**Comment by ieugen** [comment]
Hi, 

I have the same issue here. 
I just discovered the project and looks great.
Tried it with  a cron to do a curl. Made a mistake and I could not tell easily if it's failing of not. 
I still don't know WHY it's failing since I don't see anything in logs yet.

**Comment by crazy-max** [comment]
I get your point but it's not the purpose of swarm-cronjob to track if a command for a service succeed or not. It's up to the service itself to report this kind of issue.
