### ISSUE TITLE
Feature request: cli to manually run a job?

### ISSUE THREAD

**Issue by hgl** [crazy-max/swarm-cronjob#19]
Sometimes manually running a job is desired, like migrating db etc. The job doesn't have to be run repeatedly.

I wonder if it makes sense to offer a cli that can instruct swarm-cronjob to run a job immediately?

Ideally the cli could offer arguments similar to that of `docker run` where you can override entry point, working dir, etc.

**Comment by crazy-max** [comment]
@hgl No, that's not swarm-cronjob's goal here, sorry.
