### ISSUE TITLE
Update service's schedule

### ISSUE THREAD

**Issue by dejan9393** [crazy-max/swarm-cronjob#23]
Is it possible to have the cron schedule updated when the service's labels change?

For example, i'm running Docker Swarm and there's a stack running; one service in the stack has the labels to let swarm-cronjob know that it is a cron task.
I update the `swarm.cronjob.schedule` label in `docker-compose.yml` and run a `docker stack deploy` - swarm-cronjob would notice the change and re-schedule this cron task.

My current workaround is `docker service remove {cron_service}` before deploy.

Thanks!

**Comment by crazy-max** [comment]
@dejan9393 It must be already available. If a service event is triggered, swarm-cronjob will check and update cronjob against this service. If you think there is a bug here, please create a [bug report](https://github.com/crazy-max/swarm-cronjob/issues/new?template=bug_report.md).
