### ISSUE TITLE
Concatenate jobs

### ISSUE THREAD

**Issue by colthreepv** [crazy-max/swarm-cronjob#26]
Hi, this is a feature request / general question

There are several scenarios when multiple commands have to be issued on a cronjob, and they belong to very different Docker Images  
An example of this could be backupping a mysql database and then uploading such payload to a cloud provider, let's say dropbox

For such a scenario, a developer could build a third image containing both `mysql` binaries and `dbxcli`, and with that newly created Image, build a script that can do both the actions: [backup, upload]

Another scenario could be having 2 containers sharing a volume, the first one executing the backup procedure, and then following one to be the one uploading, maybe those containers don't even need a script file, but just _one command_ each

This could lead to an higher reuse of public docker images, do you think it could be achieved?  
Do you see hard limitations on this happening?

**Comment by ashtuchkin** [comment]
You could probably start both containers on schedule and then the uploader could wait for the exporter to finish by e.g. watching for a special file in the shared volume.

For more advanced logic a separate scheduler like Airflow should work, not sure cronjob is the right place to put it into.
