### ISSUE TITLE
Log when edit swarm.cronjob.schedule label

### ISSUE THREAD

**Issue by gustavopaes** [crazy-max/swarm-cronjob#29]
### Behaviour

Log when cronjob time is updated via docker swarm label.

#### Steps to reproduce this issue

1. Create a service `xxx` in your `nnn` stack with swarm-cronjob labels to activate cronjob;
2. swarm-cronjob log will log the message:
`Mon, 02 Mar 2020 13:41:43 -03 INF Add cronjob with schedule 45 * * * * service=nnn_xxxx`
3. Update the label `swarm.cronjob.schedule`
4. Not will be logged in `swarm-cronjob` container;

#### Expected behaviour

Maybe log something in `swarm-cronjob` container:
`Mon, 02 Mar 2020 13:41:43 -03 INF Updated cronjob with schedule 55 * * * * service=nnn_xxxx`

#### Actual behaviour

Nothing is logged when label `swarm.cronjob.schedule` is updated

### Configuration

* Target Docker version (the host/cluster you manage) : 19.03.5
* Platform (windows/linux) : linux
* System info (type `uname -a`) : Linux swarm3 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Logs

> Mon, 02 Mar 2020 13:27:26 -03 INF Starting swarm-cronjob 1.7.1
> Mon, 02 Mar 2020 13:41:43 -03 INF Add cronjob with schedule 45 * * * * service=nnn_xxx
> Mon, 02 Mar 2020 13:45:00 -03 INF Start job service=nnn_xxx status= tasks_active=0
> Mon, 02 Mar 2020 13:55:00 -03 INF Start job service=nnn_xxx status= tasks_active=0
> Mon, 02 Mar 2020 14:05:00 -03 INF Start job service=nnn_xxx status= tasks_active=0

**Comment by gustavopaes** [comment]
Actually the log exists, but it's flagged as `debug`:
https://github.com/crazy-max/swarm-cronjob/blob/master/internal/app/app.go#L174

Is it purposeful or a mistake?

**Comment by crazy-max** [comment]
@gustavopaes That's on purpose. This log is an event involving the update of the stack, the service and also its execution via swarm-cronjob. To avoid flooding the logs, it is put in debug mode.
