### ISSUE TITLE
Docker Swarm Config Ignored

### ISSUE THREAD

**Issue by Mikkyo** [crazy-max/swarm-cronjob#3]
### Behaviour
Hi there,

It seems that if you put a "configs" in your docker-compose swarm file, and you try to run this container onto the your CRON system, the configuration is totally ignored. I made a quick fix to avoid any problem with this behavior. but it will be great if it doesn't happen. 
 
#### Steps to reproduce this issue

1. Having a docker-compose with a config file 
deploy: 
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=55 * * * * *"
        - "swarm.cronjob.skip-running=false"
      replicas : 0
      restart_policy:
        condition: none
    configs:
      - source : app_config
        target : /app/config.json

configs :
  app_config:
    file : ./config.json

2. Make this service under swarm-cronjob
3. Launch it

#### Expected behaviour
My service is to rename specific file to start different services, so it should just do his normal execution then stop.

#### Actual behaviour
It simply can't find the file anymore, it was working perfectly when I didn't update his behavior to be on swarm-cronjob.

Traceback (most recent call last):
  File "index.py", line 43, in <module>
    with open("./config.json", 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: './config.json'

### Configuration
* Target Docker version (the host/cluster you manage) : 
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:23 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:02:44 2019
  OS/Arch:          linux/amd64
  Experimental:     false

* Platform (windows/linux) : Linux
* Target Swarm version : 

### Docker info
Containers: 53
 Running: 10
 Paused: 0
 Stopped: 43
Images: 90
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: r3n35izga6bm62qe3ukavh90n
 Is Manager: true
 ClusterID: mejy5e45rpv3qi5c31brgj75z
 Managers: 1
 Nodes: 1
 Default Address Pool: 10.0.0.0/8  
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.11.228
 Manager Addresses:
  192.168.11.228:2377
Runtimes: nvidia runc
Default Runtime: nvidia
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb-dirty
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-131-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 48
Total Memory: 125.8GiB
Name: gpu-dev
ID: TSWA:FM46:HGP5:XN25:G4K2:T6RW:UZIO:2KRN:DNV4:FIN2:CRRA:3ALK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://registry.docker-cn.com/
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support

### Logs
See earlier in the actual output

I really appreciate your work and hope it will grow into something big ! Cheers

**Comment by crazy-max** [comment]
Hi @Mikkyo, I was able to reproduce your issue. What is your current Compose file format ?

**Comment by crazy-max** [comment]
After an update some specs are removed :

![image](https://user-images.githubusercontent.com/1951866/51544006-34ea2f80-1e5f-11e9-9e7c-db76b1c7c714.png)
> https://www.diffchecker.com/9sZrPsYj

It seems there is a [workaround](https://github.com/moby/moby/issues/35048#issuecomment-424372653) for that using `name` parameter but instead using this I will add a new implementation for this behaviour. I keep you in touch and thans for your support!

**Comment by crazy-max** [comment]
@Mikkyo Should be ok with the latest release

**Comment by Mikkyo** [comment]
Thank you for your quick work ! I will try and keep you updated ok ?

**Comment by crazy-max** [comment]
@Mikkyo Nice thanks :)
