### ISSUE TITLE
After Updating docker container no longer starts. it starts and immadiatley fails.

### ISSUE THREAD

**Issue by awptechnologies** [crazy-max/swarm-cronjob#307]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/swarm-cronjob/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [ ] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

crazymax swarmcron not running after update

### Expected behaviour

container to run.

### Actual behaviour

container will not start and stay running.

### Steps to reproduce

update to latest docker version

### swarm-cronjob version

latest

### Docker info

```text
cant post this as it contains ips and usernames for registries.
```

### Logs

```text
no logs container wont let run long enough all i get is an exit code
```

**Comment by mcarim** [comment]
I'm also facing the same issue. After upgrading docker in Ubuntu 22.04 LTS, swarm-cronjob is failing:

$ docker service logs traefik_swarm-cronjob
traefik_swarm-cronjob.1.7wyv6xf91a6q@ip-172-31-10-224    | Fri, 19 Jan 2024 18:06:57 -03 INF Starting swarm-cronjob v1.12.0
traefik_swarm-cronjob.1.7wyv6xf91a6q@ip-172-31-10-224    | Fri, 19 Jan 2024 18:06:57 -03 FTL Cannot initialize swarm-cronjob error="Error response from daemon: client version 1.12 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version"

$ docker version
Client: Docker Engine - Community
 Version:           25.0.0
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        e758fe5
 Built:             Thu Jan 18 17:09:49 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.0
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       615dfdf
  Built:            Thu Jan 18 17:09:49 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.27
  GitCommit:        a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc:
  Version:          1.1.11
  GitCommit:        v1.1.11-0-g4bccb38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by awptechnologies** [comment]
i will parse all my personal info out and post docker info to see if its the same....

Client: Docker Engine - Community
 Version:           25.0.0
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        e758fe5
 Built:             Thu Jan 18 17:09:59 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.0
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       615dfdf
  Built:            Thu Jan 18 17:09:59 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.27
  GitCommit:        a1496014c916f9e62104b33d1bb5bd03b0858e59
 nvidia:
  Version:          1.1.11
  GitCommit:        v1.1.11-0-g4bccb38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by bolet** [comment]
I replaced all image versions in Dockerfile with their "latest" versions, hoping a simple rebuild would solve the issue. It didn't.
Next step: dive into go sources / dependencies.

**Comment by bolet** [comment]
This fixes the issue, but I'm not an expert in go, so I won't make a PR.
Meanwhile if my "hack" helps anyone, here it is: 
```
diff --git a/internal/docker/client.go b/internal/docker/client.go
index 226a85a..e25418f 100644
--- a/internal/docker/client.go
+++ b/internal/docker/client.go
@@ -34,7 +34,7 @@ type DockerClient struct {
 
 // NewEnvClient initializes a new Docker API client based on environment variables
 func NewEnvClient() (*DockerClient, error) {
-       dockerAPICli, err := client.NewClientWithOpts(client.FromEnv, client.WithVersion("1.12"))
+       dockerAPICli, err := client.NewClientWithOpts(client.FromEnv, client.WithVersion("1.24"))
        if err != nil {
                return nil, errors.Wrap(err, "failed to initialize Docker API client")
        }
```

**Comment by awptechnologies** [comment]
Any idea when this will be added to the image for people that don't know how to do that?

**Comment by bolet** [comment]
> Any idea when this will be added to the image for people that don't know how to do that?

I expect the official fix to come very soon, but if you can't wait it's easy to apply my fix yourself.
You don't need any tools other than `docker`. In short:
1. download the sources of this repo (through `git clone` or as a zip)
2. make the change (in file `internal/docker/client.go`, line 34, replace `1.12` with `1.24`)
3. from the root of the source directory, where you find `Dockerfile`, run `docker build -t yourownimage .`
4. use `yourownimage` instead of `crazymax/swarm-cronjob`

**Comment by tomdaley92** [comment]
> I'm also facing the same issue. After upgrading docker in Ubuntu 22.04 LTS, swarm-cronjob is failing:
> 
> $ docker service logs traefik_swarm-cronjob traefik_swarm-cronjob.1.7wyv6xf91a6q@ip-172-31-10-224 | Fri, 19 Jan 2024 18:06:57 -03 INF Starting swarm-cronjob v1.12.0 traefik_swarm-cronjob.1.7wyv6xf91a6q@ip-172-31-10-224 | Fri, 19 Jan 2024 18:06:57 -03 FTL Cannot initialize swarm-cronjob error="Error response from daemon: client version 1.12 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version"
> 
> $ docker version Client: Docker Engine - Community Version: 25.0.0 API version: 1.44 Go version: go1.21.6 Git commit: e758fe5 Built: Thu Jan 18 17:09:49 2024 OS/Arch: linux/amd64 Context: default
> 
> Server: Docker Engine - Community Engine: Version: 25.0.0 API version: 1.44 (minimum version 1.24) Go version: go1.21.6 Git commit: 615dfdf Built: Thu Jan 18 17:09:49 2024 OS/Arch: linux/amd64 Experimental: false containerd: Version: 1.6.27 GitCommit: a1496014c916f9e62104b33d1bb5bd03b0858e59 runc: Version: 1.1.11 GitCommit: v1.1.11-0-g4bccb38 docker-init: Version: 0.19.0 GitCommit: de40ad0

Same here.

**Comment by crazy-max** [comment]
https://github.com/crazy-max/swarm-cronjob/pull/313 should fix this issue
