### ISSUE TITLE
-- Question -- Mariabackup with swarm cronjob

### ISSUE THREAD

**Issue by bd8392** [crazy-max/swarm-cronjob#35]
Hi =), I want to use your container with mariabackup (included in maraidb official docker container) to make backups (as this is not possible in swarm). Have you tried it out and have you maybe an example for that? Do I have to mount the mariadb config to the cron also? Does it somehow interfere with my databases? For example if I use another container for mariabackup, does it crash my databases?

**Comment by crazy-max** [comment]
Hi @bd8392, here is a basic example: https://github.com/crazy-max/swarm-cronjob/blob/master/.res/example/mariadb_dump.yml

**Comment by bd8392** [comment]
Very cool thanks :-)

BlueMail for Android<http://www.bluemail.me/r?b=15824> herunterladen
Am 26. Apr. 2020, um 15:23, CrazyMax <notifications@github.com<mailto:notifications@github.com>> schrieb:

Hi @bd8392<https://github.com/bd8392>, here is a basic example: https://github.com/crazy-max/swarm-cronjob/blob/master/.res/example/mariadb_dump.yml
