### ISSUE TITLE
renovate/renovate does not run when invoked by swarm-cronjob

### ISSUE THREAD

**Issue by decentral1se** [crazy-max/swarm-cronjob#41]
(Thanks for this project!)

### Behaviour

I am trying to run renovate bot to upgrade my configs on a cron job using this project. The cronjob is registered and it is scheduled but the job does not run. I see nothing in the logs for the actual scheduled container. I have tried to use `healthcheck: disable` but this doesn't seem to work either.

My configs:
- swarm-cronjob: https://git.autonomic.zone/autonomic-cooperative/swarm-cronjob
- renovate: https://git.autonomic.zone/autonomic-cooperative/renovate

Refs:
- https://docs.renovatebot.com/
- https://hub.docker.com/r/renovate/renovate/

#### Steps to reproduce this issue

1. Setup a docker swarm setup (single node cluster works)
1. `git clone https://git.autonomic.zone/autonomic-cooperative/swarm-cronjob`
2. `cd swarm-cronjob && docker stack deploy -c docker-compose.yml -c docker-compose.production.yml swam-cronjob`
3. `git clone https://git.autonomic.zone/autonomic-cooperative/renovate`
4. `cd renovate && docker stack deploy -c docker-compose.yml -c docker-compose.production.yml renovate`

#### Expected behaviour

The renovate bot container should run.

#### Actual behaviour

The renovate bot container does not run.

### Configuration

* Target Docker version (the host/cluster you manage) : Docker swarm single host cluster
* Platform (windows/linux) : linux
* System info (type `uname -a`) : Linux my-swarm 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
* Target Swarm version : Latest

### Docker info

```
Client:
 Debug Mode: false
Server:
 Containers: 9
  Running: 7
  Paused: 0
  Stopped: 2
 Images: 17
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: barfoo
  Is Manager: true
  ClusterID: foobar
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 116.203.211.204
  Manager Addresses:
   116.203.211.204:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-8-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.902GiB
 Name: my-swarm
 ID: 6RXL:N5JJ:O3QC:5R7U:OYDN:63HG:27Z7:2VQK:W5M5:PIKY:LMCJ:PYFI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: bingbong
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Logs

```
swarm-cronjob_docker-cron-job.1.2qw0nstpe2sy@myswarm    | Thu, 07 May 2020 08:11:01 UTC INF Start job service=renovate_renovate status=updating tasks_active=0
```

**Comment by decentral1se** [comment]
```
        "UpdateStatus": {
            "State": "updating",
            "StartedAt": "2020-05-07T08:25:01.49090233Z",
            "Message": "update in progress"
        }
```

From `docker inspect`, it appears to be stuck in "updating" mode?

**Comment by decentral1se** [comment]
Misconfigured on my side, missing volume mount and secret accessing stanza.

Sorry for the noise!

**Comment by crazy-max** [comment]
Hi @decentral1se,

If you can open a PR with your stack like I did for [`mariadb_dump.yml`](https://github.com/crazy-max/swarm-cronjob/blob/master/.res/example/mariadb_dump.yml), that would be nice!
