### ISSUE TITLE
Incorrect cron parsing

### ISSUE THREAD

**Issue by mashbrno** [crazy-max/swarm-cronjob#6]
Log is better than thousand words. Hours are swapped with minutes, instead of executing at 2am, it is running every hour at xx:02.

{"level":"debug","service":"generator","time":"2019-05-15T14:02:00Z","message":"Update cronjob with schedule 0 2 * * *"},
{"level":"debug","service":"generator","newstate":"completed","oldstate":"updating","time":"2019-05-15T14:02:00Z","message":"Event triggered"}

**Comment by crazy-max** [comment]
Cron expression format uses 6 space-separated fields. Please see : https://godoc.org/github.com/crazy-max/cron#hdr-CRON_Expression_Format

**Comment by aguiraf** [comment]
Hi @crazy-max, thank you for this useful tool!
A note: actual implementation is based on 6 fields, but the doc you linked is all about classical 5 fields cron (without seconds)

**Comment by crazy-max** [comment]
Hi @aguiraf, sorry the link is outdated (https://godoc.org/github.com/robfig/cron#hdr-CRON_Expression_Format) and now seconds field is optional.
Thanks for your support :)
