### ISSUE TITLE
Question: how to run a script on my VPS?

### ISSUE THREAD

**Issue by pascalandy** [crazy-max/swarm-cronjob#8]
What I want is to manage cron without editing the `crontab -e` on every VPS.

I see all examples are running something in a container. I want to run a script on my host.

How should I run something like `/user/mnt/my_scripts/all-nodes/fct_BackupGhostDbOnly.sh` ?

Cheers!

**Comment by crazy-max** [comment]
If you want to run command on host, `privileged` mode must be enabled for the container. But privileged services are not supported for Swarm at that time. There is moby/moby#24862 about this.

**Comment by pascalandy** [comment]
Thanks!

**Comment by crazy-max** [comment]
You should also see [this thread](https://stackoverflow.com/a/52910798/514571) about that question. Some users also use SSH to enter commands on host.
