### ISSUE TITLE
Is there a way to pass in options to start the service?

### ISSUE THREAD

**Issue by piscopoc** [crazy-max/swarm-cronjob#91]
Great project, thanks for building this!

Question though, we use a third party docker registry and some services are failing to start because the image it is referencing isn't on the host machine. Is there a way to specify start up options on the service to force it to look to the docker registry for this image when starting up?

Ideally something that would emulate the following:
```
docker service update service_name_xyz --with-registry-auth --force
```

Thanks!

**Comment by crazy-max** [comment]
Hi @piscopoc, can you test with `crazymax/swarm-cronjob:registry-auth`? I've also added a new Docker label to enable this feature called `swarm.cronjob.registry-auth`.

**Comment by piscopoc** [comment]
Hi @crazy-max, thanks for turning this around so quickly. Just trying it out right now and I will report back here shortly with the results. Assuming the ```swarm.cronjob.registry-auth``` is just a boolean, right?

**Comment by crazy-max** [comment]
@piscopoc 

> Assuming the `swarm.cronjob.registry-auth` is just a boolean, right?

Yes that's it! This will retrieve the encoded auth token from the image reference.

**Comment by piscopoc** [comment]
@crazy-max changes checks out on my end. I will try some more long-term testing with this item as well but I am already seeing immediate results with services starting correctly now.

Thanks again turning this around so quickly and for updating this excellent project with this enhancement!

**Comment by crazy-max** [comment]
@piscopoc Ok great, I will open a PR with these changes. Keep me in touch with your tests.
